language: node_js
node_js:
  - "8"

os: [linux]
dist: trusty
sudo: required
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true

install:
  - yarn
  - yarn run build

